### ISSUE TITLE
Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by davidmarcantonio** [peniqliotuv/robinhood-ticker#5]
While logging in I get that error.

**Comment by Sarithz** [comment]
Same here

**Comment by peniqliotuv** [comment]
@NemesisOfNo @Sarithz So sorry I forgot to reply to this - Robinhood made changes to their API a while back to switch to OAuth2. I released a new version that should fix this problem [here](https://github.com/peniqliotuv/robinhood-ticker/releases/tag/v3.0.0)
